### ISSUE TITLE
Implement the Metrics part of OpenTelemetry API

### ISSUE THREAD

**Issue by ethercrow** [ethercrow/opentelemetry-haskell#12]
Currently only the Trace part is implemented.

**Comment by ethercrow** [comment]
I think it would be nice to start with a Int Gauge because we already have some internal ones like thread count and heap size.

The API can be:

```
registerIntGauge :: ByteString -> IO IntGauge -- creates a gauge with a unique id and the given name, outputs both to eventlog
setIntGauge :: Int -> IntGauge -> IO () -- outputs the gauge id and the provided value to the eventlog
```

**Comment by mpardalos** [comment]
I think Gauges have been removed now. [Here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#metric-instruments) is the new spec for instruments.

I think the closest to the old Gauge right now is `ValueRecorder`? 

I have been working on support for these here: 

* [Instrument definitions](https://github.com/mpardalos/opentelemetry-haskell/blob/4b20112e0cf53ae44db65f2130266ac04a5f4be7/opentelemetry/src/OpenTelemetry/Instruments.hs#L15-L30)
* [API](https://github.com/mpardalos/opentelemetry-haskell/blob/metrics/opentelemetry/src/OpenTelemetry/Eventlog.hs#L77-L88)

The reason for the 3 different recording functions (which all do the same) and the Instruments being a GADT is the specification [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#interpretation).

**Comment by ethercrow** [comment]
Indeed it seems that ValueRecorder is a serious business speak for a Gauge. This is fine.
