### ISSUE TITLE
eventlog-to-tracy improvements

### ISSUE THREAD

**Issue by ethercrow** [ethercrow/opentelemetry-haskell#24]
1. Instead of calling `eventlog-to-chrome` executable it should call the corresponding function.

https://github.com/ethercrow/opentelemetry-haskell/blob/master/opentelemetry-extra/exe/eventlog-to-tracy/Main.hs#L22

2. It should detect missing `import-chrome` or `Tracy` executables and direct the user to instructions how to install those.

**Comment by TristanCacqueray** [comment]
Thank you for setting the `good first issue` label! It seems like this can now be closed.
