### ISSUE TITLE
Unreadable output in tracy with many threads

### ISSUE THREAD

**Issue by mpardalos** [ethercrow/opentelemetry-haskell#30]
This is the view I'm currently getting in Tracy from a ghcide trace:

![image](https://user-images.githubusercontent.com/2512446/85412074-1959eb80-b561-11ea-9bdd-4dec6e6725fc.png)
(With multiple screen-fulls of the same below)

I think, ideally, there should be an option in the tracy interface to collapse all threads into one. As a work around, we could add a `--collapse-threads` option to `eventlog-to-tracy` which would give all spans the same thread id.

**Comment by ethercrow** [comment]
Implemented `eventlog-to-tracy --collapse-threads`.
