### ISSUE TITLE
Questions about the eventlog file

### ISSUE THREAD

**Issue by psibi** [ethercrow/opentelemetry-haskell#33]
Thanks for the package! Looks quite interesting and I'm planning to use it in future for finding perf issues.

But I do have some questions (which I guess can be useful to add it in the docs):

* How big can the eventlog file get if I start storing it locally and run the program for a day or so ?
* Is this limitation still applicable: https://gitlab.haskell.org/ghc/ghc/-/wikis/event-log#limitations ? Is there a way to separate the "observer effect" from the output somehow ?

**Comment by ethercrow** [comment]
Thank you for the kind words!

> How big can the eventlog file get if I start storing it locally and run the program for a day or so ?

This depends largely on what your program is doing. How much is it allocating, how many ffi calls, how often are threads created and migrated between cores, etc.

In general for long-running programs it's expected that the evenlog is not a file but a pipe and you have some other process that reads from that pipe and ships the data elsewhere, presumably to one of the specialized services like Zipkin or Jaeger. I haven't tested this mode of operation in production yet, so it's not advertised in the readme.

> Is this limitation still applicable: https://gitlab.haskell.org/ghc/ghc/-/wikis/event-log#limitations ? Is there a way to separate the "observer effect" from the output somehow ?

I have not done any stress testing related to that. As with any instrumentation profiling tool you'd have to figure out what to instrument to have enough insight to be useful but also to not incur too much overhead.

**Comment by psibi** [comment]
Thanks!
