### ISSUE TITLE
Make GC sync visible

### ISSUE THREAD

**Issue by expipiplus1** [ethercrow/opentelemetry-haskell#42]
It would be great to hook into `longGCSync` and `longGCSyncEnd` to get the GC sync waits highlighted in the trace. It could be that these are already visible in the eventlog, in which case no hooks are needed.

(options described here: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-flag---long-gc-sync)

**Comment by ethercrow** [comment]
Interesting, I wasn't aware of these hooks or even the notion of possibly long GC sync pauses.

```
  -- garbage collection
  | RequestSeqGC       { }
  | RequestParGC       { }
  | StartGC            { }
  | GCWork             { }
  | GCIdle             { }
  | GCDone             { }
  | EndGC              { }
  | GlobalSyncGC       { }
  | GCStatsGHC         { heapCapset   :: {-# UNPACK #-}!Capset
                       , gen          :: {-# UNPACK #-}!Int
                       , copied       :: {-# UNPACK #-}!Word64
                       , slop, frag   :: {-# UNPACK #-}!Word64
                       , parNThreads  :: {-# UNPACK #-}!Int
                       , parMaxCopied :: {-# UNPACK #-}!Word64
                       , parTotCopied :: {-# UNPACK #-}!Word64
                       }

```

If I understand the eventlog protocol [here](https://github.com/maoe/ghc-events/blob/c17a996a81c412f64c51bae53a0483d03b2e019d/src/GHC/RTS/EventTypes.hs#L204) correctly, this pause is the period between `Request*GC` and `StartGC`.

Currently we emit `gc` spans according to `StartGC` and `EndGC` events, it's done [here](https://github.com/ethercrow/opentelemetry-haskell/blob/9bbdfa8f9e281bd78a8937d04defbb1867a55b86/opentelemetry-extra/src/OpenTelemetry/EventlogStreaming_Internal.hs#L170). I guess adding an appropriate handler for `Request*GC` would be enough to have GC syncs represented in trace data.

I'll probably have time for it on a weekend. If you want to do it that's also cool.

**Comment by expipiplus1** [comment]
I don't think that I have the time for it soon, but I'm not in any massive hurry either!

**Comment by ethercrow** [comment]
Now there are `gc_sync` spans:

<img width="1933" alt="Screen Shot 2020-12-07 at 7 29 21 AM" src="https://user-images.githubusercontent.com/222467/101317061-0c565d80-385e-11eb-81df-fb9319842899.png">

**Comment by expipiplus1** [comment]
Amazing! Thank you!

**Comment by expipiplus1** [comment]
@bgamari ^

**Comment by bgamari** [comment]
Indeed the meaning of these events has never been well documented. Since you pinged I finally added some proper documentation: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4580. Do comment on the MR if you have any questions.
