### ISSUE TITLE
Implement `eventlog-to-tracy` exporter

### ISSUE THREAD

**Issue by ethercrow** [ethercrow/opentelemetry-haskell#7]
What I do currently to view an eventlog in tracy is first execute `eventlog-to-chrome` to convert it to the Chrome Tracing format and then execute `import-chrome` utility that lives in the Tracy codebase: https://bitbucket.org/wolfpld/tracy/src/master/import-chrome/

It would be a better user experience to have a one step process instead of two step.

**Comment by yaitskov** [comment]
@ethercrow, is it about rewriting  import-chrome.cpp into Haskell and adding new command line flag to eventlog-to-chrome to activate imported feature?

**Comment by ethercrow** [comment]
@yaitskov Rewriting import-chrome.cpp in Haskell would be hard because Tracy's file format is neither stable nor documented. I think the simplest way to have a first working version of `eventlog-to-tracy` is to call `import-chrome` as subprocess.

Another thing to do would be to update `import-chrome` to import the span tags. Currently it only reads the name, thread id and timing.

**Comment by ethercrow** [comment]
This is what I use as a workaround https://gist.github.com/ethercrow/c045001c7d2e1952d8674f6c52f1dc6b

**Comment by yaitskov** [comment]
What is the reason for keeping an app per format?
Wouldn't be better to put all exporters into "convert-eventlog-to" and control target format through command line parameters?

```
convert-eventlog-to  ( zipkin | rawtext | tracy | chrome ) 
```

**Comment by yaitskov** [comment]
@ethercrow , looks like span Tags are already exported
```
c5d2a22b opentelemetry-extra/src/OpenTelemetry/ChromeExporter.hs (Dmitry Ivanov 2020-05-01 12:48:58 +0200 38)             "args" .= fmap ChromeTagValue spanTags
```
I have an idea to join keys of that map with "," and write to "cat" field.

**Comment by yaitskov** [comment]
```
main = do
  withSpan "helloWorld" $ do
         setTag "tag777" "bingo"
         putStrLn "Hello"

```
```
[
{"ts":1589251546017080,"args":{"tid":4,"tag777":"bingo"},"tid":4,"name":"helloWorld","pid":1,"ph":"B"},
{"ts":1589251546017148,"tid":4,"name":"helloWorld","pid":1,"ph":"E"}
]
```

I noticed that B and E are emitted together, could we replace B and E with one message of X type?

**Comment by yaitskov** [comment]
It's strange isn't it?
The project is called open telemetry but there is no open telemetry 
and apps convert eventlog to chrome and zipkin formats.

I would expect to have following flow:

> eventlog ---> open telemetry ---> chrome, zipkin

**Comment by ethercrow** [comment]
zipkin is one of the accepted formats for opentelemetry services.

I didn't feel the need for an intermediate representation between eventlog and all the output formats, but that could change.

**Comment by ethercrow** [comment]
> I noticed that B and E are emitted together, could we replace B and E with one message of X type?

If X events are shown in the same way in both Chrome and Tracy then sure.

**Comment by ethercrow** [comment]
> I have an idea to join keys of that map with "," and write to "cat" field.

I don't get it, how would it be useful? Some categories would look like `http.url,http.method,peer.service,error,error.message,error.stacktrace`.

**Comment by ethercrow** [comment]
> What is the reason for keeping an app per format?

Mainly because of dependencies. One user might want to send trace data to a service using gRPC+protobuf format. It is inhumane to force people who just want to build `eventlog-to-chrome` to install grpc libraries and protobuf compiler because of it.
